config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  resources :tags, only: %i(index show), param: :name
  resources :posts, except: %i(index)
  resources :users, only: %i(show)

  delete '/sign_out',             to: 'sessions#destroy', as: :sign_out
  get '/auth/:provider/callback', to: 'sessions#callback'
  get '/auth/failure',            to: 'sessions#failure'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :image, styles: { medium: '320x320>' }, convert_options: { medium: '-gravity center -background white -extent 320x320' }
  validates_attachment_presence :image
  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\Z}
  validates :body, presence: true, length: { maximum: 500 }
  validates :tags, presence: true

  before_validation :delete_post_relation, :save_tags

  belongs_to :user
  has_many :tag_posts, dependent: :destroy
  has_many :tags, through: :tag_posts

  def save_tags
    tags << Tag.where_or_create_by_names(scan_tag_names)
  end

  def delete_post_relation
    tag_posts.delete_all
  end

  def scan_tag_names
    body.scan(/#[^\s]+/).each { |name| name.sub!(/^#/, '') }
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, uniqueness: true, length: { minimum: 1, maximum: 100 }

  has_many :tag_posts
  has_many :posts, -> { order(created_at: :desc) }, through: :tag_posts

  def self.where_or_create_by_names(names)
    tags = names.map { |name| Tag.new(name: name) }
    Tag.import(tags, on_duplicate_key_update: :name)
    Tag.where(name: names)
  end
end

app/models/tag_post.rb
class TagPost < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private

  def current_user
    @_current_user ||= begin
      if (id = cookies[:_A].presence)
        User.find(id)
      end
    end
  rescue ActiveRecord::RecordNotFound
    reset_session
    redirect_to tags_path
  end

  def current_user=(user)
    return unless user
    cookies[:_A] = user.id
    @_current_user = user
  end

  def sign_out
    self.current_user = nil
    cookies[:_A] = ''
  end

  def signed_in?
    !!current_user
  end

  def require_sign_in
    redirect_to tags_path unless signed_in?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_sign_in, only: %i(new create edit update destroy)
  before_action :set_post, only: %i(show edit update destroy)

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:body, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def callback
    user = User.find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider']) do |user|
      user.name  = auth_hash['info']['name']
      user.email = auth_hash['info']['email']
      user.image = auth_hash['info']['image']
    end

    self.current_user = user
    redirect_to root_path
  end

  def failure
    reset_session
    redirect_to tags_path
  end

  def destroy
    sign_out
    redirect_to tags_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all.includes(:posts)
  end

  def show
    @tag = Tag.find_by_name!(params[:name])
    @posts = @tag.posts
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :require_sign_in, only: %i(index)

  def index
    @posts = Post.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_sign_in

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tipsy
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1' }
    %meta{ name: 'format-detection', content: 'telephone=no' }
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'shared/header'

    .content
      = yield

app/views/posts/_form.html.haml
= form_for(post) do |f|
  - if post.errors.any?
    #error_explanation
      %h2
        = pluralize(post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - post.errors.full_messages.each do |message|
          %li= message
  .field
    = f.file_field :image
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit

app/views/posts/_post_list.html.haml
.post-lists
  - posts.each do |post|
    .post
      = image_tag post.image.url(:medium), class: 'post__image'
      %div
        = image_tag post.user.image

app/views/posts/edit.html.haml
%h1 Editing Post
= render 'form', post: @post
= link_to 'Show', @post
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%p#notice= notice
%h1 Posts
%table
  %thead
    %tr
      %th Body
      %th{ colspan: 3 }
  %tbody
    - @posts.each do |post|
      %tr
        %td= image_tag post.image.url
        %td= post.body
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New Post
= render 'form', post: @post
= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice
= image_tag @post.image.url
%p
  %strong Body:
  = @post.body

= link_to 'Edit', edit_post_path(@post)
= link_to 'Back', posts_path

app/views/shared/_header.html.haml
%header
  .header-content
    = link_to 'Tipsy', root_path, class: 'header-content__logo'
    %ul.header-content__menu
      %li
        = link_to tags_path do
          %i.fa.fa-search.fa-lg
      %li
        = link_to new_post_path do
          %i.fa.fa-pencil-square-o.fa-lg
      %li
        - if signed_in?
          = link_to user_path(current_user.id) do
            = image_tag(current_user.image)
        - else
          = link_to tags_path do
            %i.fa.fa-user.fa-lg

app/views/tags/index.html.haml
- unless signed_in?
  = link_to 'facebook　ログイン', '/auth/facebook', class: 'btn btn-primary btn-lg btn-block'

.tag-lists
  - @tags.each do |tag|
    .tag
      = link_to tag_path(name: tag.name) do
        %h2.tag__name= tag.name
        .tag__images
          - tag.posts.take(3).each do |post|
            = image_tag post.image.url(:medium), class: 'tag__image'

app/views/tags/show.html.haml
= render 'posts/post_list', posts: @tag.posts

app/views/top/index.html.haml
= render 'posts/post_list', posts: @posts

app/views/users/show.html.haml
= @user.name